global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.1.243:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node-vm1:9100', 'node-vm2:9100'] # replace with your VMware VMs' IPs or hostnames
  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
    - targets: ['192.168.1.250:8080'] # replace with your Jenkins VMware VM's IP or hostname
